from pipesandfilters import Filter, SourceFilter, SinkFilter, Pipe, Pipeline

sink = SinkFilter(1, abs)
filter = Filter(1, abs)
source = SourceFilter(1, abs)
p = Pipe(source, sink)
# source.run(3)
# p.run()
# sink.run()
pipeline = Pipeline("lol")
pipeline.setSourceFilter(source)
pipeline.addSinkFilter(sink)
pipeline.validate()
pipeline.myGraphViz()
pipeline.run(2)
